{% set name = "TileDB" %}
{% set version = "2.17.4" %}
{% set commit = "a1f648e" %}
{% set sha256 = "5070b3477a7fe07d5f7815e5f2ff3d683db59aeb6b7df1428616dafb8d9ff306" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/releases/download/{{ version }}/tiledb-linux-x86_64-{{ version }}-{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', min_pin='x.x', max_pin='x.x') }}
  skip: true  # [not linux]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h
    - test -e $PREFIX/include/tiledb/tiledb
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
    - jdblischak
