{% set name = "TileDB" %}
{% set version = "2.18.2" %}
{% set pkg_version = "cloud-2.18-awssdk-1.8.2" %}
{% set commit = "82cd615" %}
{% set sha256 = "86f0c3e15bb1a0091b9f4ebac3aa28a91af9ac3306a04601ccb6aa041c08857b" %}

package:
  name: tiledb
  version: {{ version }}

source:
  # HEY! RESET TO TileDB-Inc
  url: https://github.com/ihnorton/{{ name }}/releases/download/{{ pkg_version }}/tiledb-linux-x86_64-noavx2-{{ pkg_version }}-{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', min_pin='x.x', max_pin='x.x') }}
  skip: true  # [not linux]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h
    - test -e $PREFIX/include/tiledb/tiledb
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
    - jdblischak
