{% set name = "TileDB" %}
{% set version = "2.17.0" %}
{% set commit = "93c173d" %}
{% set sha256 = "065e4a335813d9e6c3e3d80b4073965953bf84dd04cb2aef6c7ce1e8667ba575" %}

package:
  name: tiledb
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/releases/download/{{ version }}/tiledb-linux-x86_64-{{ version }}-{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', min_pin='x.x', max_pin='x.x') }}
  skip: true  # [not linux]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h
    - test -e $PREFIX/include/tiledb/tiledb
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
    - jdblischak
