azure:
  store_build_artifacts: True
  upload_packages: True
  build_id: 51
  user_or_org: TileDB-Inc
  project_name: CI
channels:
  sources:
    - conda-forge
  targets:
    - ["tiledb", "for-cloud"]
conda_forge_output_validation: False
github:
  user_or_org: TileDB-Inc
  repo_name: tiledb-feedstock-for-cloud
provider:
  linux_64: azure
